from django.contrib import admin
from .models import *
from django.apps import apps

admin.site.register(Member)
admin.site.register(MemberDetails)
admin.site.register(Mentor)
admin.site.register(ManualEnrollment)
admin.site.register(RecordedCourse)
admin.site.register(RecordedCourseAssignmentSubmission)
admin.site.register(RecordedCourseModule)
admin.site.register(RecordedCourseNotification)
admin.site.register(RecordedCourseProgressTracking)
admin.site.register(LiveCourse)
admin.site.register(LiveCourseModule)
admin.site.register(LiveCourseModuleClass)
admin.site.register(Blog)
admin.site.register(BlogComment)
admin.site.register(Book)
admin.site.register(Question)
admin.site.register(QuizResult)
admin.site.register(Certificate)
admin.site.register(ClassPermissionTracking)
admin.site.register(Enrolled)
admin.site.register(Faq)
admin.site.register(Purchased)
admin.site.register(Invoice)
admin.site.register(Inquiry)